Base.create!([
  {team_id: 3, latitude: 41.8721722, longitude: -87.6187505},
  {team_id: 4, latitude: 41.9208947, longitude: -87.6456607},
  {team_id: 1, latitude: 41.8922115, longitude: -87.6348112},
  {team_id: 5, latitude: 41.8921903, longitude: -87.6348099},
  {team_id: 2, latitude: 41.8921832, longitude: -87.634832}
])
Capture.create!([
  {flag_id: 1, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 1, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 3, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 3, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 4, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 4, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 4, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 5, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 3, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 6, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 5, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 2, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 7, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 10, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 11, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 9, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 7, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 14, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 13, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 15, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 17, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 16, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 18, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 20, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 23, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 19, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 21, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 22, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 12, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 22, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 26, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 22, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 28, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 29, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 24, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 29, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 30, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 27, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 30, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 31, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 33, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 32, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 34, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 35, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 36, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 36, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 38, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 39, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 39, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 37, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 41, user_id: 1, dropped_time: nil, success: true},
  {flag_id: 42, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 42, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 40, user_id: 2, dropped_time: nil, success: true},
  {flag_id: 43, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 43, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 46, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 46, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 46, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 46, user_id: 2, dropped_time: nil, success: false},
  {flag_id: 46, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 47, user_id: 3, dropped_time: nil, success: false},
  {flag_id: 47, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 47, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 47, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 47, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 48, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 48, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 49, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 49, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 50, user_id: 5, dropped_time: nil, success: false},
  {flag_id: 50, user_id: 4, dropped_time: nil, success: false},
  {flag_id: 51, user_id: 1, dropped_time: nil, success: false},
  {flag_id: 51, user_id: 3, dropped_time: nil, success: true},
  {flag_id: 52, user_id: 3, dropped_time: nil, success: true},
  {flag_id: 53, user_id: 3, dropped_time: nil, success: true}
])
Flag.create!([
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 2},
  {latitude: nil, longitude: nil, team_id: nil, base_id: 1},
  {latitude: 41.9208947, longitude: -87.6456607, team_id: 4, base_id: 2},
  {latitude: 41.8721722, longitude: -87.6187505, team_id: 3, base_id: 1},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: nil, longitude: nil, team_id: 1, base_id: 3},
  {latitude: 41.8922115, longitude: -87.6348112, team_id: 1, base_id: 3}
])
Stun.create!([
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 3},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 2, stunnee_id: 1},
  {stunner_id: 2, stunnee_id: 4},
  {stunner_id: 3, stunnee_id: 2},
  {stunner_id: 4, stunnee_id: 3},
  {stunner_id: 2, stunnee_id: 4},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 4},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 3},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 4, stunnee_id: 3},
  {stunner_id: 1, stunnee_id: 2},
  {stunner_id: 1, stunnee_id: 4},
  {stunner_id: 1, stunnee_id: 3},
  {stunner_id: 4, stunnee_id: 3},
  {stunner_id: 4, stunnee_id: 2},
  {stunner_id: 4, stunnee_id: 5},
  {stunner_id: 4, stunnee_id: 1},
  {stunner_id: 4, stunnee_id: 5},
  {stunner_id: 1, stunnee_id: 4},
  {stunner_id: 3, stunnee_id: 1}
])
Team.create!([
  {name: "Red", score: 0, image: "https://qph.ec.quoracdn.net/main-qimg-07bf6aa86a755a2d12e866be5c8fccbf"},
  {name: "Blue", score: 0, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Solid_blue.svg/225px-Solid_blue.svg.png"},
  {name: "Green", score: 18, image: "http://greensportsalliance.org/images/darkGreenSquare.gif"},
  {name: "Yellow", score: 9, image: "http://is1.mzstatic.com/image/thumb/Purple128/v4/f1/a7/cf/f1a7cf1f-77fa-0f3c-670b-49a2e8eb8689/source/1200x630bb.jpg"},
  {name: "Purple", score: 3, image: "http://images.hellogiggles.com/uploads/2015/03/08/purple-suede.jpg"}
])
User.create!([
  {name: "Mitch", email: "mitchfischer6@gmail.com", team_id: 4, points: 1040, latitude: 41.8922181, longitude: -87.6347786, password_digest: "$2a$10$28N8zLBxymPLlbYrPtCque7mfKxeRr9lstukyMN9jn/bZbWp200ke", has_flag: false, time_stunned: "2017-11-14 02:45:41"},
  {name: "Mr. Gray", email: "grayboy@gmail.com", team_id: 5, points: 154, latitude: 41.8922038, longitude: -87.6347812, password_digest: "$2a$10$lcN.b61e.9gxpACn2w18beo4NshWhjEc2Pr1zEvcL8GYmMSa0I0ma", has_flag: false, time_stunned: nil},
  {name: "Mr. Peanutbutter", email: "pbj@gmail.com", team_id: 3, points: 524, latitude: 41.8921832, longitude: -87.634832, password_digest: "$2a$10$WUE47n2R.ZctJN5NAtoWhevGKNUe0RDkUsh5/ponjnwMUwk2fk/9q", has_flag: false, time_stunned: nil},
  {name: "My Friend Jacque", email: "jacque@myfriend.org", team_id: 4, points: 0, latitude: 41.8921962, longitude: -87.6348725, password_digest: "$2a$10$khgD9xb6M24iC1cvRVTqR.hAIjoDT/2Dz7/O4GKFrPdy2qwIigyQ2", has_flag: false, time_stunned: nil},
  {name: "Pizza Boy", email: "THEPIZZA@PIZZA.com", team_id: 1, points: 86, latitude: 41.892181, longitude: -87.6349216, password_digest: "$2a$10$1eFtZq/UUJ.7SvOZYyAgt.eVMCHpkDmLy51aQH/UZTepDJCnGf3za", has_flag: false, time_stunned: nil}
])
